spring.data.mongodb.uri=mongodb+srv://hieuhb4321:66771508@se-dev.j8rls6c.mongodb.net/?retryWrites=true&w=majority&appName=SE-DEV
//spring.data.mongodb.uri=mongodb://localhost:27017/
spring.data.mongodb.database=media-shop
server.port=8080
